client:
  callback-url: "http://localhost:8080/api/v1/callback"
spring:
  profiles:
    active: secret
feign:
  client:
    config:
      auth:
        request-interceptors[0]: com.kinandcarta.musicfriends.auth.AuthClientInterceptor
artist:
  search:
    url: https://blah.com